# ~/.tmux.conf

# ==== GENERAL CONFIGURATION ====

# Enable mouse
set -g mouse on

# Enable shared clipboard
set -g set-clipboard on

# Start window/pane indexing at 1
set -g base-index 1
setw -g pane-base-index 1

# More intuitice splits (same directory)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# vi mode
setw -g mode-keys vi

# vi mode (command)
set -g status-keys vi

# selection/yank in copy mode
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'C-v' send-keys -X rectangle-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection

# moving between panes using hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resizing panes using shifted-HJKL
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# timeout for binds 500ms -> 1s
set -g repeat-time 1000

# Recalculate windows when one is closed
set -g renumber-windows on

# ==== STYLING ====

# status bar
set -g status-style "fg=black,bg=colour117"

# window
setw -g window-status-current-style "fg=white,bg=blue,bold"
setw -g window-status-style "fg=black,bg=colour117"

# panes
set -g pane-border-style "fg=blue"
set -g pane-active-border-style "fg=brightblue"
set -g pane-border-lines double




